networks:
  defaults:
    external:
      name: roboshop
services:
  # docker run -d --name mongodb --network roboshop mongodb:v1
  mongodb:
    image: mongodb:v1
    # networks:          # disabling as we have given the network in the root
    #   - roboshop
  
  catalogue:
    image: catalogue:v1
    # networks:
    #   - roboshop
    depends_on:
      - mongodb

  web:
    image: web:v1
    # networks:
    #   - roboshop
    ports:
      - "80:80"
    depends_on:
      - catalogue
  
  redis:
    image: redis

  user:
    image: user:v1
    depends_on:
      - mongodb
      - redis
  cart: 
    image: cart:v1
    depends_on:
      - redis      
      - catalogue
