networks:
  defaults:
    external:
      name: roboshop
services:
  # docker run -d --name mongodb --network roboshop mongodb:v1
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    # networks:          # disabling as we have given the network in the root
    #   - roboshop
  
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    # networks:
    #   - roboshop
    depends_on:
      - mongodb

  web:
    image: web:v1
    container_name: web
    # networks:
    #   - roboshop
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
  
  redis:
    image: redis
    container_name: redis

  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart: 
    image: cart:v1
    container_name: cart
    depends_on:
      - redis      
      - catalogue
  mysql:
    image: mysql:v1
    container_name: mysql
  
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
      - cart
      - mysql
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123

  payment:
    image: payment:v1
    container_name: payment
    depends_on:
      - cart
      - user
      - rabbitmq

